# Sampling configuration for scripts/batch_rollout.py
#
# You can pass this file with:
#   python scripts/batch_rollout.py --config config/sampling_config.yaml \
#     --num-samples 2000 --input-data input_data.csv --time-range 2015 2035 --seed 123
#
# Notes:
# - Distributions supported: fixed, uniform, normal, lognormal, beta, choice
# - normal supports optional min/max with clip_to_bounds: true
# - lognormal uses parameters in log space: mu, sigma; supports min/max with clip_to_bounds
# - beta draws in [0,1] then scales to [min,max]
# - choice supports optional probabilities p

seed: 32432432
initial_progress: 0.0
# If omitted on CLI, this is used; otherwise CLI --time-range overrides
time_range: [2012.0, 2040.0]

num_rollouts: 5000
input_data: input_data.csv

parameters:
  # Superhuman coder time horizon + extrapolation
  sc_time_horizon_minutes:
    dist: lognormal
    mu: 11.73  # ~124560 minutes
    sigma: 1.0
    min: 1000.0
    max: 100000000000.0
    clip_to_bounds: true
  horizon_extrapolation_type:
    dist: choice
    values: ["exponential", "decaying doubling time"]
    p: [0.25, 0.75]

  # Manual horizon fitting (used when horizon_extrapolation_type="decaying doubling time")
  present_day:
    dist: fixed
    value: 2025.25
  present_horizon:
    dist: fixed
    value: 15.0
  present_doubling_time:
    dist: lognormal
    mu: -0.776  # ~0.46
    sigma: 0.3
    min: 0.01
    max: 2.0
    clip_to_bounds: true
  doubling_decay_rate:
    dist: beta
    alpha: 0.5
    beta: 10.0
    min: 0.000001
    max: 0.5
    clip_to_bounds: true

  
  # coding labor
  rho_coding_labor:
    dist: fixed
    value: -2.0
  coding_labor_normalization:
    dist: fixed
    value: 1.0

  # experiment capacity
  rho_experiment_capacity:
    dist: fixed
    value: -0.137
  alpha_experiment_capacity:
    dist: fixed
    value: 0.70

  experiment_compute_exponent:
    dist: fixed
    value: 0.56

  # Automation
  automation_fraction_at_superhuman_coder:
    dist: fixed
    value: 1.00
  swe_multiplier_at_present_day:
    dist: normal
    mean: 1.05
    sd: 0.2
    min: 1.0
    max: 10.0
    clip_to_bounds: true

  # Research taste dynamics
  ai_research_taste_at_superhuman_coder_sd:
    dist: normal
    mean: 0.0
    sd: 0.2
    min: -10.0
    max: 23.0
    clip_to_bounds: true
  ai_research_taste_slope:
    dist: lognormal
    mu: 1.5  # ~2.0
    sigma: 0.5
    min: 0.1
    max: 10.0
    clip_to_bounds: true
  taste_schedule_type:
    dist: fixed
    value: "SDs per effective OOM"

  # Software scale / normalization
  r_software:
    dist: fixed
    value: 2.40

  # Baseline annual compute multiplier
  baseline_annual_compute_multiplier:
    dist: fixed
    value: 4.5

  # Coding labor exponent
  coding_labor_exponent:
    dist: fixed
    value: 0.5
